config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  post 'posts' => 'posts#create', as: 'create_post'
  put 'posts/:id' => 'posts#update', as: 'update_post'
  delete 'posts/:id' => 'posts#delete', as: 'post_delete'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @post = Post.new
    @posts = Post.all
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to root_path
    else
      @posts = Post.all
      render :index
    end
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to root_path
    else
      @posts = Post.all
      render :index
    end
  end

  def delete
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to root_path
  end

  private
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DeleteApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<h1>Posts#index</h1>
<p>Find me in app/views/posts/index.html.erb</p>
<%= form_for @post, url: create_post_path do |f| %>
  title:<%= f.text_field :title %><br/>
  body:<%= f.text_area :body %><br/>
  <%= f.submit %><br/>
<% end %>

<% @posts.each do |post| %>

  <%= form_tag("/posts/#{post.id}", method: :put ) do %>
    <input type="text" name="post[title]" value="<%= post.title %>" />
    <textarea name="post[body]"><%= post.body %></textarea>
    <input type="submit" value="Update" />
  <% end %>
  <%= link_to "削除", post_delete_path(post.id), method: :delete %>

<% end %>